### ISSUE TITLE
Give newer speakers an opportunity (and the support they need)

### ISSUE THREAD

**Issue by sophiekoonin** [kitze/awesome-conference-practices#10]
During the talk selection process, don't disregard speakers who don't have much speaking experience. Be the person who gives them that experience! It's also really helpful to offer your speakers support from volunteer mentors (usually experienced speakers) if they want to practice their talk or get advice.

**Comment by sdras** [comment]
React Rally did a great thing where they paired two speakers up to run through a practice session. I _think_ they were pairing up people with different experience levels but similar interests, which worked super well! The experienced speaker got the benefit of hearing from someone without curse of knowledge, and the inexperienced speaker got tips on what it would be like/how to connect with the audience. Highly recommended!
