### ISSUE TITLE
Access to fitness equipment of some sort

### ISSUE THREAD

**Issue by benlesh** [kitze/awesome-conference-practices#4]
Some speakers (and attendees) have a fitness regimen they'd like to stick to. Even a modest hotel fitness center is a huge plus. Sometimes a conference will require a speaker to travel for almost a whole week. That's a long time to put off exercise.

**Comment by kitze** [comment]
@benlesh Couldn't agree more. I'm always googling for "gyms around me" which can be a PITA.  Just added it!
